routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index');

Route::get('questions/user', 'QuestionController@user')->name('questions.user');
Route::resource('questions', 'QuestionController')->only([
    'index', 'create', 'store', 'show'
]);

Route::resource('answers', 'AnswerController')->only([
    'store'
]);

Route::post('upvotes/select', 'UpvoteController@select');
Route::resource('upvotes', 'UpvoteController')->only([
    'store'
]);

Route::get('/logout', 'Auth\LoginController@logout')->name('logout' );

Route::get('/admin/users',  'AdminController@users')->name('admin.users' );
Route::get('/admin/users/{id}/login',  'AdminController@userLogin')->name('admin.user.login' );

resources/views/partials/footer.blade.php
<footer id="footer">
    <section class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="widget widget_contact">
                    <h3 class="widget_title">Exchange ?</h3>
                    <p>Un lieu d'échange convivial où toutes questions trouvera une réponse</p>
                    <p>Apprentissage de la pédagogie de l'entraide. Savoir questionner pour obtenir des réponses pertinentes</p>
                </div>
            </div>
            <div class="col-md-2">
                <div class="widget">
                    <h3 class="widget_title">Liens utiles</h3>
                    <ul>
                        <li class="{{ Request::is('/') ? 'current_page_item' : '' }}">
                            <a href="{{ url('/') }}">Accueil</a>
                        </li>
                        <li class="{{ Request::is('questions/create') ? 'current_page_item' : '' }}">
                            @if (Auth::guest())
                                <a href="{{ url('/login') }}">Poser une question</a>
                            @else
                                <a href="{{ url('/questions/create') }}">Poser une question</a>
                            @endif
                        </li>
                        <li class="">
                            <a href="{{ route('questions.index') }}">Questions</a>
                        </li>
                        @if (Auth::guest())
                            <li><a href="{{ url('/login') }}">Login</a></li>
                        @else
                            <li><a href="{{ url('/logout') }}">Logout</a></li>
                        @endif
                    </ul>
                </div>
            </div>
            <div class="col-md-6">
                    <div class="widget widget_contact">
                        <h3 class="widget_title">Intéret ?</h3>
                        <p>Créer en tant que projet back office pour la fabrique de Roanne, cette outil à vocation pédagogique a pour objectif de servir de lieu d'échange entre tous simploniens de toutes promotions.</p>
                    </div>
                </div>
            </div>
        </div><!-- End row -->
    </section><!-- End container -->
</footer><!-- End footer -->
<footer id="footer-bottom">
    <section class="container">
        <div class="copyrights f_left">Copyright 2018 Une Question ? | <a href="mailto:contact@idmkr.io">By Simplon-Roanne</a></div>
        <div class="social_icons f_right">
            <ul>
                <li class="twitter"><a original-title="Twitter" class="tooltip-n" href="#"><i class="social_icon-twitter font17"></i></a></li>
                <li class="facebook"><a original-title="Facebook" class="tooltip-n" href="#"><i class="social_icon-facebook font17"></i></a></li>
                <li class="gplus"><a original-title="Google plus" class="tooltip-n" href="#"><i class="social_icon-gplus font17"></i></a></li>
            </ul>
        </div><!-- End social_icons -->
    </section><!-- End container -->
</footer><!-- End footer-bottom -->

resources/views/partials/head.blade.php
<!-- Basic Page Needs -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<meta name="description" content="Exchange Simplon.co – Questions/réponses pour les promotions Simplon">
<meta name="author" content="Idmkr">

<!-- Mobile Specific Metas -->
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

<!-- Main Style -->
<link href="{{ asset('/css/style.css') }}" rel="stylesheet">

<!-- Skins -->
<link href="{{ asset('/css/skins/skins.css') }}" rel="stylesheet">

<!-- Responsive Style -->
<link href="{{ asset('/css/responsive.css') }}" rel="stylesheet">

<!-- Favicons -->
<link rel="shortcut icon" href="public/images/favicon.png">

<style>
	code {
            background: #eee;
	    padding: 2px 5px;
	}


</style>

@yield('styles')

resources/views/partials/header.blade.php
@if(!request()->is('/'))
    <div id="header-top">
        <section class="container clearfix">
            <nav class="header-top-nav">
                <ul>
                    @if (Auth::guest())
                        <li><a href="{{ url('/login') }}"><i class="icon-user"></i>Login Area</a></li>
                    @else
                        <li><a href="{{ url('/logout') }}">Logout</a></li>
                    @endif
                </ul>
            </nav>
            <div class="header-search">
                <form>
                    <input type="text" value="Search here ..." onfocus="if(this.value=='Search here ...')this.value='';" onblur="if(this.value=='')this.value='Search here ...';">
                    <button type="submit" class="search-submit"></button>
                </form>
            </div>
        </section><!-- End container -->
    </div><!-- End header-top -->
@endif
<header id="header">
    <section class="container clearfix">
        <div class="logo">
            <a href="{{ url('/') }}" class="font26">
                <span>Exchange</span>.Simplon
            </a>
        </div>
        <nav class="navigation">
            <ul>
                <li class="{{ Request::is('/') ? 'current_page_item' : '' }}">
                    <a href="{{ url('/') }}">Accueil</a>
                </li>
                <li class="{{ Request::is('questions/create') ? 'current_page_item' : '' }}">
                        <a href="{{ route('questions.create') }}">Poser une question</a>
                </li>
                <li class="{{ Request::is('questions') ? 'current_page_item' : '' }}">
                    <a href="{{ route('questions.index') }}">Donner une réponse</a>
                </li>
                @if (!$currentUser)
                    <li><a href="{{ url('/login') }}">Connexion</a></li>
                @else
                    <li class="{{ Request::is('questions/user') ? 'current_page_item' : '' }}">
                        <a href="{{ route('questions.user') }}">Mes questions</a>
                    </li>

                    @if($currentUser->is_admin)
                        <li><a href="{{ route('admin.users') }}">Users</a></li>
                    @endif
                    <li><a href="{{ url('/logout') }}">Déconnexion</a></li>
                @endif
            </ul>
        </nav>
	@if($currentUser)
        <div style="color: #fff;font-size: 10px;position: absolute;right: 5px;bottom: 0;">Bonjour {{ $currentUser->name }}. Tu as {{ $currentUser->points }} points de karma</div>
	@endif    
</section><!-- End container -->
</header><!-- End header -->

resources/views/partials/messages.blade.php
@if ($message = Session::get('success'))
    <div class="alert alert-success alert-block">
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($message = Session::get('error'))
    <div class="alert alert-danger alert-block">
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($message = Session::get('warning'))
    <div class="alert alert-warning alert-block">
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($message = Session::get('info'))
    <div class="alert alert-info alert-block">
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($errors->any())
    <div class="alert alert-danger">
        Please check the form below for errors
    </div>
@endif

resources/views/partials/question.blade.php
<article class="question single-question question-type-normal">
    {!!   $routeIsQuestionShow ? '':'<a href="'.url('/questions/'.$question->id).'">' !!}
        <h2>
            <span class="color">{{ $question->title }}</span>
        </h2>
    {!!  $routeIsQuestionShow ? '':'</a>' !!}
    <div class="question-author-date">
        <em>{{ $question->created_at->diffForHumans() }}</em> par <span class="color">{{ $question->user->name }}</span>
    </div>
    <div class="question-inner">
        <div class="clearfix"></div>
        <div class="comment-vote">
            <ul class="question-vote">

                @if(in_array($question->id, $userQuestionPreviousVotes))
                    <li>
                        <input type="submit" value="▲"
                               class="question-vote-up tooltip-n"
                               title='Vous avez déjà upvoté cette question'>
                    </li>
                @else
                    <li>
                        {!! Form::open(['action' => 'UpvoteController@store', 'method' => 'post']) !!}
                        {!! Form::hidden('question_id', $question->id) !!}
                        {!! Form::submit('▲', ['class' => 'question-vote-up']) !!}
                        {!! Form::close() !!}
                    </li>
                @endif
                <!--<li><a href="#" class="question-vote-down" title="Dislike"></a></li>!-->
            </ul>

            <div class="question-vote-result">
                {{count($question->upvotes)}}
            </div>
        </div>
        <div class="question-desc">
            {!! strip_tags($question->description, '<a><b><blockquote><code><del><dd><dl><dt><em><h1><h2><h3><i><kbd><li><ol><p><pre><s><sup><sub><strong><strike><ul><br><hr>') !!}
        </div>
        <!--<div class="question-details">
            <span class="question-answered question-answered-done"><i class="icon-ok"></i>Résolu</span>
        </div>
        -->
        <span class="question-comment"><a href="/questions/{{$question->id}}#commentlist"><i class="icon-comment"></i>{{ count($question->answers) }} Réponse(s)</a></span>
        <span class="question-view">👁 {{ $question->views }} vues</span>
        @if($question->hasSelectedAnswer)
            <span class="question-answered">✔️ Solution trouvée</span>
        @endif
        <!--<span class="question-view"><i class="icon-user"></i>70 views</span>!-->
        <div class="question-tags"><i class="icon-tags"></i>
            <a href="#!">{{ $question->category }}</a>
        </div>
        <div class="clearfix"></div>
    </div>
</article>

resources/views/partials/recent-questions.blade.php
<div class="widget">
    <h3 class="widget_title">Activité récente</h3>
    <ul class="related-posts">
        @forelse($recentQuestions as $recentQuestion)
            <li class="related-item">
                <h3><a href="{{ route('questions.show', ['id' => $recentQuestion->id]) }}">{{ $recentQuestion->title }}</a></h3>
                <p>{{ str_limit(strip_tags($recentQuestion->description), 120) }}</p>
                <div class="clear"></div><span>{{ $recentQuestion->created_at }}</span>
            </li>
        @empty
            <p>No questions at this moment</p>
        @endforelse
    </ul>
</div>

resources/views/partials/search.blade.php
<div class="section-warp ask-me">
    <div class="container clearfix">
        <div class="box_icon box_warp box_no_border box_no_background" box_border="transparent" box_background="transparent" box_color="#FFF">
            <div class="row">
                <div class="col-md-12">
                    <h2>Bienvenue sur Exchange.Simplon</h2>
                    <p>
                        Tous les Simplonnien.ne.s débutant.e.s font face aux mêmes problèmes/bogues/erreurs, mais n'osent pas toujours demander ou ne trouvent pas toujours les bonnes réponses.
                        <br>Sois rassuré.e, ici tu es libre de poser la question que tu veux, une réponse fiable et de confiance te sera faite par un.e autre apprenant.e, un.e ancien.ne Simplonien.ne ou un formateur.
                        <br><b>N'attend plus, pose ta question dès maintenant !</b>
                    </p>
                    <form class="form-style form-style-2">
                        <p>
                            <input type="text" id="question_title" value="Recherche une question, tu es sur de trouver une réponse." onfocus="if(this.value=='Recherche une question, tu es sur de trouver une réponse.')this.value='';" onblur="if(this.value=='')this.value='Recherche une question, tu es sur de trouver une réponse.';">
                            <i class="icon-pencil"></i>
                            <span class="color button small publish-question">Rechercher</span>
                        </p>
                    </form>
                </div>
            </div><!-- End row -->
        </div><!-- End box_icon -->
    </div><!-- End container -->
</div><!-- End section-warp -->

resources/views/partials/sidebar.blade.php
<div class="widget widget_stats">
    <h3 class="widget_title">Stats</h3>
    <div class="ul_list ul_list-icon-ok">
        <ul>
            <li>
                <i class="icon-question-sign"></i>Questions (
                    <span>{{ isset($questionsCount) ? $questionsCount : \App\Question::count() }}</span>
                )
            </li>
            <li>
                <i class="icon-comment"></i>Réponses (
                    <span>{{ isset($answersCount) ? $answersCount : \App\Answer::count() }}</span>
                )
            </li>
        </ul>
    </div>
</div>

<!--
<div class="widget widget_tag_cloud">
    <h3 class="widget_title">Tags</h3>
    <a href="#">projects</a>
    <a href="#">Portfolio</a>
    <a href="#">Wordpress</a>
    <a href="#">Html</a>
    <a href="#">Css</a>
    <a href="#">jQuery</a>
    <a href="#">2code</a>
    <a href="#">vbegy</a>
</div>
!-->